# Generated by Django 5.2.15 on 2026-06-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_created_at_alter_student_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
    ]
